.decl port2(x0:number,x1:number)
.decl switch1(x0:number,x1:number)
.decl port1(x0:number,x1:number)
.decl packet_in_l3(x0:number,x1:number,x2:number,x3:symbol,x4:symbol,x5:number)
.decl trusted_hosts(x0:symbol,x1:number)
.decl new_trusted_hosts(x0:symbol,x1:number)
.decl flow_mod_l3(x0:number,x1:symbol,x2:symbol,x3:number,x4:number)
.decl drop_l3(x0:number,x1:symbol,x2:symbol,x3:number)
.input packet_in_l3
.input port2
.input port1
.input trusted_hosts
.input switch1
new_trusted_hosts(ip1,instanceid0) :- packet_in_l3(switch0,port0,_,ip0,ip1,instanceid0),switch1(switch0,instanceid0),ip1 != ip0,port1(port0,instanceid0).
flow_mod_l3(switch0,ip0,ip1,port1,instanceid0) :- switch1(switch0,instanceid0),ip1 != ip0,port1(port0,instanceid0),packet_in_l3(switch0,port0,_,ip0,ip1,instanceid0),port2(port1,instanceid0).
flow_mod_l3(switch0,ip0,ip1,port1,instanceid0) :- ip0 != ip1,port1(port1,instanceid0),trusted_hosts(ip0,instanceid0),packet_in_l3(switch0,port0,_,ip0,ip1,instanceid0),switch1(switch0,instanceid0),port2(port0,instanceid0).
drop_l3(switch0,ip0,ip1,instanceid0) :- packet_in_l3(switch0,port0,_,ip0,ip1,instanceid0),switch1(switch0,instanceid0),port2(port0,instanceid0),!trusted_hosts(ip0,instanceid0).
.output new_trusted_hosts
.output flow_mod_l3
.output drop_l3