.decl packet_in(x0:number,x1:number,x2:number,x3:symbol,x4:symbol,x5:number,x6:number)
.decl table(x0:number,x1:symbol,x2:number,x3:number)
.decl flow_mod(x0:number,x1:symbol,x2:symbol,x3:number,x4:number)
.decl new_table(x0:number,x1:symbol,x2:number,x3:number)
.decl flood(x0:number,x1:number,x2:number)
.input packet_in
.input table
flow_mod(switch0,mac0,mac1,port1,instanceid0) :- table(switch0,mac0,_,instanceid0),packet_in(switch0,port1,_,mac1,mac0,_,instanceid0).
flow_mod(switch0,mac0,mac1,port1,instanceid0) :- packet_in(switch0,_,_,mac0,mac1,_,instanceid0),table(switch0,mac1,port1,instanceid0).
new_table(switch0,mac0,port0,instanceid0) :- packet_in(switch0,port0,_,mac0,_,_,instanceid0),!table(switch0,mac0,_,instanceid0).
flood(switch0,buf0,instanceid0) :- packet_in(switch0,_,buf0,_,mac1,_,instanceid0),!table(switch0,mac1,_,instanceid0).
.output flow_mod
.output new_table
.output flood