.decl hasQuorum(x0:number,x1:number)
.decl maxPreBallot(x0:number,x1:symbol,x2:number,x3:number,x4:number)
.decl propose(x0:number,x1:number,x2:number)
.decl null_ballot(x0:number,x1:number)
.decl send_2a(x0:number,x1:number,x2:number)
.input hasQuorum
.input maxPreBallot
.input propose
.input null_ballot
send_2a(ballot0,value0,instanceid0) :- hasQuorum(ballot0,instanceid0),propose(ballot0,value0,instanceid0),maxPreBallot(ballot0,_,ballot1,_,instanceid0),null_ballot(ballot1,instanceid0).
send_2a(ballot0,value0,instanceid0) :- maxPreBallot(ballot0,_,ballot1,value0,instanceid0),hasQuorum(ballot0,instanceid0),!null_ballot(ballot1,instanceid0).
.output send_2a