.decl Link(x0:symbol,x1:symbol,x2:number,x3:number)
.decl Path(x0:symbol,x1:symbol,x2:symbol,x3:number,x4:number)
.input Link
Path(node0,node1,nodelist0,cost0,instanceid0) :- Link(node0,node1,cost0,instanceid0),nodelist0=cat(node0,node1),node0 != node1.
Path(node0,node3,nodelist1,cost3,instanceid0) :- Path(node0,node2,nodelist0,cost1,instanceid0),Link(node2,node3,cost2,instanceid0),cost3=cost2+cost1,Link(node0,_,_,instanceid0),nodelist1=cat(nodelist0, node3), !contains(node3, nodelist0).
.output Path